# Generated by Django 4.1.4 on 2022-12-27 12:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='announcement',
            old_name='address',
            new_name='addressAnnouncement',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='address',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='address_User',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='announcement',
            name='category',
            field=models.CharField(choices=[('P', 'Primaire'), ('C', 'Collège'), ('L', 'Lycée')], max_length=1),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='image',
            field=models.ImageField(upload_to='api/annonce/images'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='modalite',
            field=models.CharField(choices=[('O', 'En ligne'), ('P', 'Présentiel')], max_length=1),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='favorites',
            field=models.ManyToManyField(blank=True, null=True, related_name='favorited_by', to='api.announcement'),
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('price', models.IntegerField()),
                ('announcement_offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.announcement')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
