# Generated by Django 4.1.4 on 2023-01-28 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_offer_price_remove_userprofile_favorites_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='address_User',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='telnumber',
            field=models.IntegerField(blank=True),
        ),
    ]
