# Generated by Django 4.1.4 on 2023-01-28 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_userprofile_address_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='address_User',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='telnumber',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
