export const recentAnnounces = [{id:1,title:"Full Taylor Swift Eras Tour 2022",user:{name:"Taylor Swift",avatar:"avatar.png"},module:"Math",status:"online",location:"Amizour, Bejaia",price:9500,level:"1AS",image:'thumbnail.jpg',isSaved:true},{id:2,title:"Full Taylor Swift Eras Tour 2022",user:{name:"Taylor Swift",avatar:"avatar.png"},module:"Math",status:"onsite",location:"Amizour, Bejaia",price:1500,level:"1AM",image:'thumbnail.jpg',isSaved:true},{title:"Full Taylor Swift Eras Tour 2022",user:{name:"Taylor Swift",avatar:"avatar.png"},module:"Math",status:"onsite",location:"Amizour, Bejaia",price:1500,level:"1AM",image:'thumbnail.jpg',isSaved:true},{id:3,title:"Full Taylor Swift Eras Tour 2022",user:{name:"Taylor Swift",avatar:"avatar.png"},module:"Math",status:"onsite",location:"Amizour, Bejaia",price:1500,level:"1AM",image:'thumbnail.jpg',isSaved:true},{id:4,title:"Full Taylor Swift Eras Tour 2022",user:{name:"Taylor Swift",avatar:"avatar.png"},module:"Math",status:"onsite",location:"Amizour, Bejaia",price:1500,level:"1AM",image:'thumbnail.jpg',isSaved:true}]
export const favAnnounces = [{id:1,name:"Nourredine Math Courses summary",user:{usernname:"Nourredine"},module:"Math",modalite:"O",location:"Amizour, Bejaia",price:1500,category:"C",isSaved:true},{id:2,name:"Nourredine Math Courses summary",user:{usernname:"Nourredine"},module:"Math",modalite:"O",location:"Amizour, Bejaia",price:9500,category:"L",isSaved:true},{id:3,name:"Nourredine Math Courses summary",user:{usernname:"Nourredine"},module:"Math",modalite:"P",location:"Amizour, Bejaia",price:2500,category:"P",isSaved:true}]
export const cardInfo = {id:1,title:"Full Taylor Swift Eras Tour 2022",user:{name:"Taylor Swift",avatar:"avatar.png"},module:"Math",status:"online",location:"Amizour, Bejaia",price:9500,level:"1AS",image:'thumbnail.jpg',isSaved:true}
export const imagesAnnounce = [{id:"1",img:"https://variety.com/wp-content/uploads/2022/11/Taylor-Swift.jpg"},{id:"2",img:"https://variety.com/wp-content/uploads/2022/11/Taylor-Swift.jpg"},{id:"3",img:"https://variety.com/wp-content/uploads/2022/11/Taylor-Swift.jpg"},{id:"4",img:"https://variety.com/wp-content/uploads/2022/11/Taylor-Swift.jpg"},{id:"5",img:"https://variety.com/wp-content/uploads/2022/11/Taylor-Swift.jpg"}] 
export const myAnnounces = [{id:1,name:"Nourredine Math Courses summary",user:{usernname:"Nourredine"},module:"Math",modalite:"O",location:"Amizour, Bejaia",price:1500,category:"C",isSaved:true},{id:2,name:"Nourredine Math Courses summary",user:{usernname:"Nourredine"},module:"Math",modalite:"O",location:"Amizour, Bejaia",price:9500,category:"L",isSaved:true},{id:3,name:"Nourredine Math Courses summary",user:{usernname:"Nourredine"},module:"Math",modalite:"P",location:"Amizour, Bejaia",price:2500,category:"P",isSaved:true}]
export const searchAnnounces = [{id:1,name:"Nourredine Math Courses summary",user:{usernname:"Nourredine"},module:"Math",modalite:"O",wilaya:16,price:1500,category:"C",isSaved:true},{id:2,name:"Nourredine Math Courses summary",user:{usernname:"Nourredine"},module:"Math",modalite:"O",wilaya:6,price:9500,category:"L",isSaved:true},{id:3,name:"Nourredine Math Courses summary",user:{usernname:"Nourredine"},module:"Math",modalite:"P",wilaya:8,price:2500,category:"P",isSaved:true}]
export const wilayas ={
    1:'Adrar',
    2: 'Chlef',
    3:'Laghouat',
    4:'Oum El Bouaghi',
    5:'Batna',
    6:'Béjaïa',
    7:'Biskra',
    8:'Béchar',
    9:'Blida',
    10:'Bouira',
    11:'Tamanrasset',
    12:'Tébessa',
    13:'Tlemcen',
    14:'Tiaret',
    15:'Tizi Ouzou',
    16:'Alger',
    17:'Djelfa',
    18:'Jijel',
    19:'Sétif',
    20:'Saïda',
    21:'Skikda',
    22:'Sidi Bel Abbès',
    23:'Annaba',
    24:'Guelma',
    25:'Constantine',
    26:'Médéa',
    27:'Mostaganem',
    28:"M'Sila",
    29:'Mascara',
    30:'Ouargla',
    31:'Oran',
    32:'El Bayadh',
    33:'Illizi',
    34:'Bordj Bou Arreridj',
    35:'Boumerdès',
    36:'El Tarf',
    37:'Tindouf',
    38:'Tissemsilt',
    39:'El Oued',
    40:'Khenchela',
    41:'Souk Ahras',
    42:'Tipaza',
    43:'Mila',
    44:'Aïn Defla',
    45:'Naâma',
    46:'Aïn Témouchent',
    47:'Ghardaïa',
    48:'Relizane',
    49:'Timimoun',
    50:'Bordj Badji Mokhtar',
    51:'Ouled Djellal',
    52:'Béni Abbès',
    53:'In Salah',
    54:'In Guezzam',
    55:'Touggourt',
    56:'Djanet',
    57:"El M'Ghair",
    58:'El Meniaa'
};