from selenium import webdriver
from selenium.webdriver.chrome.service import Service
from selenium.webdriver.common.by import By
from time import sleep
driver = webdriver.Chrome()
driver.get("http://localhost:3000/")
#sleep(2)
driver.find_element("id","plus").click()
#sleep(2)
driver.find_element("id","title").send_keys("Cours noureddine Math")
driver.find_element("id","desc").send_keys("Cours noureddine Math hayla top prix taylor swift bla bla bla bla")
#sleep(0.5)
driver.find_element("id","level").click()
driver.find_element("id","primaire").click()
driver.find_element("id","module").send_keys("Math")
#sleep(0.5)
driver.find_element("id","status").click()
driver.find_element("id","onsite").click()
driver.find_element("id","price").send_keys("1500")
#sleep(0.5)
driver.find_element("id","wilayas").send_keys("Bejaia")
driver.find_element("id","commune").send_keys("Amizour")
driver.find_element("id","address").send_keys("corneilla street 20021")
#driver.find_element("id","img-input").send_keys("C:\\Users\\LENOVO IP330\\Downloads\\1626269277984.jpg")
#sleep(1)
driver.find_element("id","btn-submit").click()
sleep(10)