# Generated by Django 4.1.4 on 2022-12-27 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_address_announcement_addressannouncement_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='address_User',
            field=models.CharField(default='', max_length=200),
        ),
    ]
